In [ ]:
#datasource: https://www.kaggle.com/new-york-city/nyc-parking-tickets.
#The aggregated data for the 4 files is 8 GB, approx 42.3 Million records ,so not loading the source data to GitHub project folder

In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
import os
destdir = './'

files = [ f for f in os.listdir(destdir) if os.path.isfile(os.path.join(destdir,f)) ]

In [3]:
files

['New_York_parking_ticket_data.csv',
 'parking_tickets_exploration.ipynb',
 'Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv',
 'Parking_Violations_Issued_-_Fiscal_Year_2015.csv',
 'Parking_Violations_Issued_-_Fiscal_Year_2016.csv',
 'Parking_Violations_Issued_-_Fiscal_Year_2017.csv',
 'queries.sql']

In [4]:
#Load the csv files

files[0]

df_2014 = pd.read_csv('Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv',nrows=100000 ,low_memory=False)
df_2014=df_2014.dropna(axis=1, how='all')

df_2015 = pd.read_csv('Parking_Violations_Issued_-_Fiscal_Year_2015.csv',nrows=100000,low_memory=False)
df_2015=df_2015.dropna(axis=1, how='all')

df_2016= pd.read_csv('Parking_Violations_Issued_-_Fiscal_Year_2016.csv',nrows=100000,low_memory=False)
df_2016=df_2016.dropna(axis=1, how='all')

df_2017 = pd.read_csv('Parking_Violations_Issued_-_Fiscal_Year_2017.csv',nrows=100000,low_memory=False)
df_2017=df_2017.dropna(axis=1, how='all')

# df_2014.head()
# df_2014.columns

In [5]:
df_2014.shape

(100000, 40)

In [6]:
#Creation and clean-up of dataframes.Few unwanted columns were dropped as well as NAN values were removed
#The data was filtered for some specific values,like Registration state='NY',Vehical type='Passanger' and vehicle body type='4 door sedan'
# 2014
df2014 = pd.DataFrame(df_2014,columns=['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency','Issuer Precinct','Violation County', 'Vehicle Year', 'Violation Post Code', 'Violation Description'])
df2014=df2014[df2014['Registration State']=='NY']
df2014=df2014[df2014['Plate Type']=='PAS'] 
df2014=df2014[ df2014['Vehicle Body Type']=='4DSD']
df2014.reset_index(inplace=True,drop=True)
df2014.head()

#2015
df2015 = pd.DataFrame(df_2015,columns=['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency','Issuer Precinct','Violation County', 'Vehicle Year', 'Violation Post Code', 'Violation Description'])
df2015=df2015[df2015['Registration State']=='NY']
df2015=df2015[df2015['Plate Type']=='PAS'] 
df2015=df2015[ df2015['Vehicle Body Type']=='4DSD']
df2015.reset_index(inplace=True,drop=True)
df2015.head()

#2016
df2016 = pd.DataFrame(df_2016,columns=['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency','Issuer Precinct','Violation County', 'Vehicle Year', 'Violation Post Code', 'Violation Description'])
df2016=df2016[df2016['Registration State']=='NY']
df2016=df2016[df2016['Plate Type']=='PAS'] 
df2016=df2016[ df2016['Vehicle Body Type']=='4DSD']
df2016.reset_index(inplace=True,drop=True)
df2016.head()


#2017
df2017 = pd.DataFrame(df_2017,columns=['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency','Issuer Precinct','Violation County', 'Vehicle Year', 'Violation Post Code', 'Violation Description'])
df2017=df2017[df2017['Registration State']=='NY']
df2017=df2017[df2017['Plate Type']=='PAS'] 
df2017=df2017[ df2017['Vehicle Body Type']=='4DSD']
df2017.reset_index(inplace=True,drop=True)
df2017.head()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Issuer Precinct,Violation County,Vehicle Year,Violation Post Code,Violation Description
0,7959486440,GYF2052,NY,PAS,07/07/2016,71,4DSD,VOLKS,T,120,R,2012,C-PM,71-Insp. Sticker Missing (NYS
1,8556155431,HFB9919,NY,PAS,05/26/2017,75,4DSD,DODGE,T,114,Q,2013,25-A,75-No Match-Plate/Reg. Sticker
2,8466021980,GSC6098,NY,PAS,12/27/2016,50,4DSD,NISSA,T,102,Q,2009,40 4,50-Crosswalk
3,4628712840,CBE9063,NY,PAS,12/22/2016,36,4DSD,TOYOT,V,0,BX,2008,NaN,PHTO SCHOOL ZN SPEED VIOLATION
4,4629806404,GSY2361,NY,PAS,01/23/2017,36,4DSD,BMW,V,0,QN,2011,NaN,PHTO SCHOOL ZN SPEED VIOLATION

In [7]:
df2014.shape
df2015.shape
df2016.shape
df2017.shape

(20358, 14)

In [8]:
#the data for 4 years is concatenated/appended in a single dataframe
parking_df=pd.concat([df2014, df2015, df2016, df2017], axis=0)

In [9]:
parking_df.shape

(62984, 14)

In [10]:
#the final data frame is cleaned for NAN values
parking_df.dropna()
parking_df.tail()
parking_df.shape

(62984, 14)

In [11]:
parking_df['Violation County'].value_counts()

Q     11676
K     10279
NY     7121
BX     6496
BK     2191
QN     1864
R       814
ST      401
MN      153
Name: Violation County, dtype: int64

In [12]:
parking_df.head()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Issuer Precinct,Violation County,Vehicle Year,Violation Post Code,Violation Description
0,4001470007,N131MF,NY,PAS,07/22/2013,5,4DSD,TOYOT,V,0,NaN,1997,NaN,BUS LANE VIOLATION
1,4001470056,GEW4568,NY,PAS,07/22/2013,5,4DSD,CHEVR,V,0,NaN,1999,NaN,BUS LANE VIOLATION
2,4001470287,GBW4796,NY,PAS,07/22/2013,5,4DSD,CHEVR,V,0,NaN,1998,NaN,BUS LANE VIOLATION
3,4001470627,GCK8372,NY,PAS,07/22/2013,5,4DSD,HONDA,V,0,NaN,2012,NaN,BUS LANE VIOLATION
4,4001470925,GEJ1568,NY,PAS,07/22/2013,5,4DSD,INFIN,V,0,NaN,2001,NaN,BUS LANE VIOLATION

In [13]:
#the final data frame is cleaned for NAN values
parking_df=parking_df.dropna()

In [14]:
parking_df.shape

(35606, 14)

In [15]:
parking_df.head()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Issuer Precinct,Violation County,Vehicle Year,Violation Post Code,Violation Description
3300,7000121117,GDX4085,NY,PAS,08/23/2013,21,4DSD,TOYOT,T,114,Q,0,H -,21-No Parking (street clean)
3301,7000121154,GDS7875,NY,PAS,08/23/2013,21,4DSD,HONDA,T,114,Q,2001,H -,21-No Parking (street clean)
3302,7000121166,GBC7971,NY,PAS,08/23/2013,21,4DSD,HYUND,T,114,Q,2001,H -,21-No Parking (street clean)
3303,7000121221,GFW4203,NY,PAS,08/23/2013,21,4DSD,NISSA,T,114,Q,2006,H -,21-No Parking (street clean)
3304,7000121282,GEM5081,NY,PAS,08/23/2013,21,4DSD,HONDA,T,114,Q,2012,H -,21-No Parking (street clean)

In [16]:
#index was reset for the dataframe
parking_df.reset_index(drop=True)

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Issuer Precinct,Violation County,Vehicle Year,Violation Post Code,Violation Description
0,7000121117,GDX4085,NY,PAS,08/23/2013,21,4DSD,TOYOT,T,114,Q,0,H -,21-No Parking (street clean)
1,7000121154,GDS7875,NY,PAS,08/23/2013,21,4DSD,HONDA,T,114,Q,2001,H -,21-No Parking (street clean)
2,7000121166,GBC7971,NY,PAS,08/23/2013,21,4DSD,HYUND,T,114,Q,2001,H -,21-No Parking (street clean)
3,7000121221,GFW4203,NY,PAS,08/23/2013,21,4DSD,NISSA,T,114,Q,2006,H -,21-No Parking (street clean)
4,7000121282,GEM5081,NY,PAS,08/23/2013,21,4DSD,HONDA,T,114,Q,2012,H -,21-No Parking (street clean)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35601,7005834136,GUH1293,NY,PAS,07/07/2016,20,4DSD,NISSA,T,110,Q,2011,12-A,20A-No Parking (Non-COM)
35602,8497750536,GWH8813,NY,PAS,01/27/2017,14,4DSD,ME/BE,T,14,NY,0,113,14-No Standing
35603,7393477087,EUG4295,NY,PAS,07/21/2016,71,4DSD,TOYOT,T,52,BX,2005,44 2,71A-Insp Sticker Expired (NYS)
35604,8544103406,HMV1662,NY,PAS,05/27/2017,14,4DSD,VOLKS,T,78,K,2017,56,14-No Standing
35605,8128031909,HCJ3411,NY,PAS,11/01/2016,71,4DSD,MAZDA,T,52,BX,2006,29 2,71A-Insp Sticker Expired (NYS)

In [17]:
parking_df.columns

Index(['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency', 'Issuer Precinct', 'Violation County', 'Vehicle Year',
       'Violation Post Code', 'Violation Description'],
      dtype='object')

In [18]:
# string = "19 Nov 2015  18:45:00.000"
# date = datetime.datetime.strptime(string, "%d %b %Y  %H:%M:%S.%f")

# print (date)

In [19]:
import datetime as dt

#Extracting Year from the 'Issue Date' column

# parking_df['Issue Date'] = parking_df['Issue Date'].apply(
# lambda x: pd.to_datetime(x).strftime('%m/%d/%Y')[0])

# parking_df['year']=pd.to_datetime(parking_df['Issue Date'], format='%m/%d/%Y').dt.year

# parking_df['year']=parking_df['Issue Date'].str.extract(r'([0-9][0-9][0-9][0-9])', expand=True)
parking_df['is_date']=pd.to_datetime(parking_df['Issue Date'])
parking_df['year']=parking_df['is_date'].dt.year

In [20]:
parking_df.columns

Index(['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency', 'Issuer Precinct', 'Violation County', 'Vehicle Year',
       'Violation Post Code', 'Violation Description', 'is_date', 'year'],
      dtype='object')

In [21]:
parking_df.head()
parking_df.reset_index(drop=True)

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Issuer Precinct,Violation County,Vehicle Year,Violation Post Code,Violation Description,is_date,year
0,7000121117,GDX4085,NY,PAS,08/23/2013,21,4DSD,TOYOT,T,114,Q,0,H -,21-No Parking (street clean),2013-08-23,2013
1,7000121154,GDS7875,NY,PAS,08/23/2013,21,4DSD,HONDA,T,114,Q,2001,H -,21-No Parking (street clean),2013-08-23,2013
2,7000121166,GBC7971,NY,PAS,08/23/2013,21,4DSD,HYUND,T,114,Q,2001,H -,21-No Parking (street clean),2013-08-23,2013
3,7000121221,GFW4203,NY,PAS,08/23/2013,21,4DSD,NISSA,T,114,Q,2006,H -,21-No Parking (street clean),2013-08-23,2013
4,7000121282,GEM5081,NY,PAS,08/23/2013,21,4DSD,HONDA,T,114,Q,2012,H -,21-No Parking (street clean),2013-08-23,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35601,7005834136,GUH1293,NY,PAS,07/07/2016,20,4DSD,NISSA,T,110,Q,2011,12-A,20A-No Parking (Non-COM),2016-07-07,2016
35602,8497750536,GWH8813,NY,PAS,01/27/2017,14,4DSD,ME/BE,T,14,NY,0,113,14-No Standing,2017-01-27,2017
35603,7393477087,EUG4295,NY,PAS,07/21/2016,71,4DSD,TOYOT,T,52,BX,2005,44 2,71A-Insp Sticker Expired (NYS),2016-07-21,2016
35604,8544103406,HMV1662,NY,PAS,05/27/2017,14,4DSD,VOLKS,T,78,K,2017,56,14-No Standing,2017-05-27,2017
35605,8128031909,HCJ3411,NY,PAS,11/01/2016,71,4DSD,MAZDA,T,52,BX,2006,29 2,71A-Insp Sticker Expired (NYS),2016-11-01,2016

In [22]:
parking_df.dtypes

Summons Number                    int64
Plate ID                         object
Registration State               object
Plate Type                       object
Issue Date                       object
Violation Code                    int64
Vehicle Body Type                object
Vehicle Make                     object
Issuing Agency                   object
Issuer Precinct                   int64
Violation County                 object
Vehicle Year                      int64
Violation Post Code              object
Violation Description            object
is_date                  datetime64[ns]
year                              int64
dtype: object

In [23]:
parking_df.to_csv('New_York_parking_ticket_data.csv')